name       : gpodder
version    : 3.10.16
release    : 16
source     :
    - https://github.com/gpodder/gpodder/archive/3.10.16.tar.gz : ff1441d7fc1c0eface0f4136fb71c4a8d2615486e5569fad2695df6bf9622d7f
homepage   : http://gpodder.org/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : The gPodder podcast client
description: |
    gPodder is a simple, open source podcast client written in Python using GTK+. In development since 2005 with a proven, mature codebase.
builddeps  :
    - python-coverage
    - python-minimock
    - python-mygpoclient
    - python-podcastparser
rundeps    :
    - python-gobject
    - python-html5lib
    - python-mygpoclient
    - python-podcastparser
    - python3-dbus
    - youtube-dl
install    : |
    %make_install
check      : |
    PYTHON=python3 make unittest
