name       : gpodder
version    : 3.11.2
release    : 23
source     :
    - https://github.com/gpodder/gpodder/archive/refs/tags/3.11.2.tar.gz : a8e7eb3778698c63e9ff2066253746644428573654edcfd21e46bebdc57f5d28
homepage   : https://gpodder.github.io/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : The gPodder podcast client
description: |
    gPodder is a simple, open source podcast client written in Python using GTK+. In development since 2005 with a proven, mature codebase.
builddeps  :
    - python-html5lib
    - python-mygpoclient
    - python-podcastparser
    - python-pytest
    - python-pytest-httpserver
    - python-requests
rundeps    :
    - python-gobject
    - python-html5lib
    - python-mygpoclient
    - python-podcastparser
    - python-requests
    - python3-dbus
    - yt-dlp
install    : |
    %make_install
check      : |
    %python3_test pytest3 -v
