name       : gpodder
version    : 3.9.3
release    : 2
source     :
    - https://github.com/gpodder/gpodder/archive/gpodder-3.9.3.tar.gz : 2cb80ec532ae3929f13ccf9463ffba9a9c0c7ec8b723abdae34ba641131835c0
license    : GPL-3.0
component  : multimedia.audio
summary    : Gpodder Podcast Client
description: |
    gPodder is a simple, open source podcast client written in Python using GTK+. In development since 2005 with a proven, mature codebase.
rundeps    :
    - python-podcastparser
    - python-mygpoclient
    - python-gtk2
setup      : |
    %python_setup
install    : |
    %make_install
