name       : gpodder
version    : 3.10.1
release    : 6
source     :
    - https://github.com/gpodder/gpodder/archive/3.10.1.tar.gz : cd3f65146fa202c2861d8f0a2fa212323830c6c437a272f6f88a5e03581e9e0b
license    : GPL-3.0
component  : multimedia.audio
summary    : Gpodder Podcast Client
description: |
    gPodder is a simple, open source podcast client written in Python using GTK+. In development since 2005 with a proven, mature codebase.
builddeps  :
    - python-coverage
    - python-html5lib
    - python-minimock
    - python-mygpoclient
    - python-podcastparser
rundeps    :
    - python-html5lib
    - python-mygpoclient
    - python-podcastparser
    - python3-dbus
    - python3-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-util-Stop-being-a-complete-spanner.patch
install    : |
    %make_install
check      : |
    PYTHON=python3 make unittest
