name       : gpodder
version    : 3.10.21
release    : 20
source     :
    - https://github.com/gpodder/gpodder/archive/refs/tags/3.10.21.tar.gz : 014e619de64d3e3dc8493929af8007b3caf09dd77e153bf778f1708d55946878
homepage   : https://gpodder.github.io/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : The gPodder podcast client
description: |
    gPodder is a simple, open source podcast client written in Python using GTK+. In development since 2005 with a proven, mature codebase.
builddeps  :
    - python-html5lib
    - python-mygpoclient
    - python-podcastparser
    - python-pytest
    - python-pytest-httpserver
    - python-requests
rundeps    :
    - python-gobject
    - python-html5lib
    - python-mygpoclient
    - python-podcastparser
    - python-requests
    - python3-dbus
    - yt-dlp
setup      : |
    %patch -p1 < $pkgfiles/0001-Replace-youtube-dl-with-yt-dlp.patch
install    : |
    %make_install
check      : |
    %python3_test pytest3 -v
